### PR TITLE
Project 6 - Responsive Design

### PR DESCRIPTION
**Pull request by expjazz**
- We used both flexbox and grid to experiment with those tools and to get a sense of how they work. 

-We used media queries to make the page responsive to different screen sizes.

-We also chose a font that we think would suit the project better.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi Team 👋

Great job on this @expjazz  and @praz99 👌🎉🎉

Your project looks awesome.

However, kindly view this 👉(screencast)[https://www.loom.com/share/2e8172cbae7244d0a78424c514f87903] and make the changes noted there.

- [ ] Required - In addition also use this [tool](https://validator.w3.org/nu/#file) to validate your HTML file and fix the errors shown there.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by expjazz** [comment]
We made the requested changes to the gradient on the layout of the main screen and added the margin to the latest deals section. We also passed the HTML through the validator.

**Review by men32z — APPROVED** [review]
## Good job making the changes, you can merge.

BlgS1sdIUAEybkW

### Status Approved

--Luis Preza

**Pull request merged**
